## Next word Predictor

In [1]:
file_path = "my_sentences.txt"

In [2]:
# Open the file and read its contents
with open(file_path, 'r') as file:
    txt = file.read()
    
print(txt[:500])  # Displaying the first 500 characters to verify the content

I hope this email finds you well.
I am writing to inform you about...
Kindly be advised that...
I would like to bring to your attention that...
Please consider this as a formal request for...
I trust this email finds you in good health.
In accordance with our previous discussion...
I am pleased to inform you that...
Attached herewith, please find...
I would appreciate it if you could...
Per our conversation...
Thank you for your prompt response.
Your cooperation in this matter is highly apprecia


In [3]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

2024-06-19 14:54:05.469043: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-06-19 14:54:05.469141: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-06-19 14:54:05.644367: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


In [4]:
tokenizer = Tokenizer()

In [5]:
tokenizer.fit_on_texts([txt])

In [6]:
tokenizer.word_index

{'the': 1,
 'to': 2,
 'your': 3,
 'i': 4,
 'of': 5,
 'for': 6,
 'a': 7,
 'is': 8,
 'and': 9,
 'in': 10,
 'you': 11,
 'we': 12,
 'our': 13,
 'on': 14,
 'team': 15,
 'this': 16,
 'upcoming': 17,
 'recent': 18,
 'attached': 19,
 'are': 20,
 'with': 21,
 'please': 22,
 'am': 23,
 'project': 24,
 'my': 25,
 'appreciate': 26,
 'that': 27,
 "i'm": 28,
 "let's": 29,
 'meeting': 30,
 'support': 31,
 "i'll": 32,
 'find': 33,
 'feedback': 34,
 'work': 35,
 'foster': 36,
 'would': 37,
 'positive': 38,
 'collaboration': 39,
 'attention': 40,
 "it's": 41,
 'time': 42,
 'like': 43,
 'can': 44,
 'about': 45,
 'matter': 46,
 'need': 47,
 'acknowledge': 48,
 'be': 49,
 "what's": 50,
 'it': 51,
 'any': 52,
 'success': 53,
 'details': 54,
 'provide': 55,
 'wanted': 56,
 'encourage': 57,
 'writing': 58,
 'new': 59,
 'culture': 60,
 'have': 61,
 'discuss': 62,
 'me': 63,
 'value': 64,
 "where's": 65,
 'as': 66,
 'cooperation': 67,
 'commitment': 68,
 'will': 69,
 'prompt': 70,
 'review': 71,
 'training': 72

In [7]:
token_len = len(tokenizer.word_index)   # we need this later, length of vocabulary
print(token_len)

2030


In [8]:
# Splitting text into sentences on the basis of '.' or we can use '\n' for upon the basis of newline change
for sentence in txt.split('.'):
    print(sentence)

I hope this email finds you well

I am writing to inform you about



Kindly be advised that



I would like to bring to your attention that



Please consider this as a formal request for



I trust this email finds you in good health

In accordance with our previous discussion



I am pleased to inform you that



Attached herewith, please find



I would appreciate it if you could



Per our conversation



Thank you for your prompt response

Your cooperation in this matter is highly appreciated

I would like to express my gratitude for



In reference to our recent meeting



Please find the attached document for your review

Enclosed, you will find



I am writing to seek clarification on



I would like to bring to your attention the following issue



As per your request



I am reaching out to you regarding



I trust you will find the information provided useful

Your immediate attention to this matter is requested

We would like to inform you that



Please find below the det

In [9]:
# Tokenized presentation of all the sentences as list of numbers(tokens)
for sentence in txt.split('.'):
   tokenized_sentence = tokenizer.texts_to_sequences([sentence])
   print(tokenized_sentence)

[[4, 145, 16, 151, 173, 11, 128]]
[[4, 23, 58, 2, 80, 11, 45]]
[[]]
[[]]
[[180, 49, 209, 27]]
[[]]
[[]]
[[4, 37, 43, 2, 174, 2, 3, 40, 27]]
[[]]
[[]]
[[22, 483, 16, 66, 7, 843, 90, 6]]
[[]]
[[]]
[[4, 110, 16, 151, 173, 11, 10, 293, 411]]
[[10, 1019, 21, 13, 442, 268]]
[[]]
[[]]
[[4, 23, 116, 2, 80, 11, 27]]
[[]]
[[]]
[[19, 140, 22, 33]]
[[]]
[[]]
[[4, 37, 26, 51, 122, 11, 77]]
[[]]
[[]]
[[730, 13, 1020]]
[[]]
[[]]
[[194, 11, 6, 3, 70, 93]]
[[3, 67, 10, 16, 46, 8, 134, 97]]
[[4, 37, 43, 2, 106, 25, 107, 6]]
[[]]
[[]]
[[10, 484, 2, 13, 18, 30]]
[[]]
[[]]
[[22, 33, 1, 19, 227, 6, 3, 71]]
[[195, 11, 69, 33]]
[[]]
[[]]
[[4, 23, 58, 2, 228, 243, 14]]
[[]]
[[]]
[[4, 37, 43, 2, 174, 2, 3, 40, 1, 640, 152]]
[[]]
[[]]
[[66, 730, 3, 90]]
[[]]
[[]]
[[4, 23, 146, 85, 2, 11, 117]]
[[]]
[[]]
[[4, 110, 11, 69, 33, 1, 86, 581, 1334]]
[[3, 220, 40, 2, 16, 46, 8, 82]]
[[12, 37, 43, 2, 80, 11, 27]]
[[]]
[[]]
[[22, 33, 582, 1, 54, 5]]
[[]]
[[]]
[[4, 23, 58, 2, 254, 165, 14, 13, 268]]
[[]]
[[]]
[[4, 26, 3, 

In [10]:
input_sequences = []
for sentence in txt.split('.'):
    tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]

    for i in range(1,len(tokenized_sentence)):
        input_sequences.append(tokenized_sentence[:i+1])

In [11]:
# we can see the sequence of the words, taking each new words as input from the sentence

input_sequences

[[4, 145],
 [4, 145, 16],
 [4, 145, 16, 151],
 [4, 145, 16, 151, 173],
 [4, 145, 16, 151, 173, 11],
 [4, 145, 16, 151, 173, 11, 128],
 [4, 23],
 [4, 23, 58],
 [4, 23, 58, 2],
 [4, 23, 58, 2, 80],
 [4, 23, 58, 2, 80, 11],
 [4, 23, 58, 2, 80, 11, 45],
 [180, 49],
 [180, 49, 209],
 [180, 49, 209, 27],
 [4, 37],
 [4, 37, 43],
 [4, 37, 43, 2],
 [4, 37, 43, 2, 174],
 [4, 37, 43, 2, 174, 2],
 [4, 37, 43, 2, 174, 2, 3],
 [4, 37, 43, 2, 174, 2, 3, 40],
 [4, 37, 43, 2, 174, 2, 3, 40, 27],
 [22, 483],
 [22, 483, 16],
 [22, 483, 16, 66],
 [22, 483, 16, 66, 7],
 [22, 483, 16, 66, 7, 843],
 [22, 483, 16, 66, 7, 843, 90],
 [22, 483, 16, 66, 7, 843, 90, 6],
 [4, 110],
 [4, 110, 16],
 [4, 110, 16, 151],
 [4, 110, 16, 151, 173],
 [4, 110, 16, 151, 173, 11],
 [4, 110, 16, 151, 173, 11, 10],
 [4, 110, 16, 151, 173, 11, 10, 293],
 [4, 110, 16, 151, 173, 11, 10, 293, 411],
 [10, 1019],
 [10, 1019, 21],
 [10, 1019, 21, 13],
 [10, 1019, 21, 13, 442],
 [10, 1019, 21, 13, 442, 268],
 [4, 23],
 [4, 23, 116],
 [4

Here, we can see size of each row is not same, it's not suitable input for the supervised learning, so now we use zero padding fo this

In [12]:
# we need to know the max-length of the sequence
max_length = max([len(x) for x in input_sequences])
print(max_length)

1678


In [13]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences = pad_sequences(input_sequences, maxlen = max_length, padding = 'pre')

print(padded_input_sequences)

[[  0   0   0 ...   0   4 145]
 [  0   0   0 ...   4 145  16]
 [  0   0   0 ... 145  16 151]
 ...
 [  0   0   0 ... 171   9 347]
 [  0   0   0 ...   9 347 434]
 [  0   0   0 ... 347 434 289]]


In [14]:
X = padded_input_sequences[:,:-1] # we kept all the rows and all columns except the last item in the column

y = padded_input_sequences[:,-1] # we kept all rows but only the last column

In [15]:
print(X)

[[  0   0   0 ...   0   0   4]
 [  0   0   0 ...   0   4 145]
 [  0   0   0 ...   4 145  16]
 ...
 [  0   0   0 ...   7 171   9]
 [  0   0   0 ... 171   9 347]
 [  0   0   0 ...   9 347 434]]


In [16]:
X.shape

(24291, 1677)

In [17]:
print(y)

[145  16 151 ... 347 434 289]


In [18]:
from tensorflow.keras.utils import to_categorical

y = to_categorical(y, num_classes = token_len+1)

# we did token_len+1 because tokenizer started from 1 instead of zero, where OHE starts from zero

In [19]:
print(y)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [20]:
y.shape

(24291, 2031)

## Model Training

In [21]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [22]:
model = Sequential()
model.add(Embedding(token_len+1, 100,input_length = max_length-1))  
# parameters: size of vocabulary, dimension of embeddings, length of each sentence in input( reduced by 1 as last column is taken as y)
model.add(LSTM(150))   # 150 nodes in LSTm gates
model.add(Dense(token_len+1, activation = 'softmax') )

/opt/conda/lib/python3.10/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [23]:
model.compile(loss = 'categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [24]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [25]:
model.fit(X,y, epochs=25)

Epoch 1/25
760/760 ━━━━━━━━━━━━━━━━━━━━ 49s 60ms/step - accuracy: 0.0702 - loss: 6.1652
Epoch 2/25
760/760 ━━━━━━━━━━━━━━━━━━━━ 46s 61ms/step - accuracy: 0.1655 - loss: 4.9117
Epoch 3/25
760/760 ━━━━━━━━━━━━━━━━━━━━ 46s 61ms/step - accuracy: 0.2582 - loss: 4.0898
Epoch 4/25
760/760 ━━━━━━━━━━━━━━━━━━━━ 46s 61ms/step - accuracy: 0.3292 - loss: 3.4921
Epoch 5/25
760/760 ━━━━━━━━━━━━━━━━━━━━ 46s 61ms/step - accuracy: 0.3863 - loss: 3.0534
Epoch 6/25
760/760 ━━━━━━━━━━━━━━━━━━━━ 46s 61ms/step - accuracy: 0.4295 - loss: 2.6986
Epoch 7/25
760/760 ━━━━━━━━━━━━━━━━━━━━ 46s 61ms/step - accuracy: 0.4694 - loss: 2.4337
Epoch 8/25
760/760 ━━━━━━━━━━━━━━━━━━━━ 46s 61ms/step - accuracy: 0.5007 - loss: 2.2047
Epoch 9/25
760/760 ━━━━━━━━━━━━━━━━━━━━ 46s 61ms/step - accuracy: 0.5346 - loss: 1.9868
Epoch 10/25
760/760 ━━━━━━━━━━━━━━━━━━━━ 46s 61ms/step - accuracy: 0.5577 - loss: 1.8359
Epoch 11/25
760/760 ━━━━━━━━━━━━━━━━━━━━ 46s 61ms/step - accuracy: 0.5913 - loss: 1.6695
Epoch 12/25
760/760 ━━━━━━━━━━

To predict multiple words

In [27]:
text = 'if you'


for i in range(5):
    #tokenize
    token_text = tokenizer.texts_to_sequences([text])[0]
    #padding
    padded_token_text = pad_sequences([token_text], maxlen = max_length-1 , padding='pre')

    #predict
    pred = model.predict(padded_token_text)

    # finding the position i.e token
    pos = np.argmax(pred)
    print(pos)

    # Decoding token into word
    for word,index in tokenizer.word_index.items():
        if index == pos:
            text = text + " " + word # It adds the o/p again to the i/p and make next prediction
            print(text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
61
if you have
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
52
if you have any
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
147
if you have any further
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
530
if you have any further questions
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
309
if you have any further questions feel
